name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build .exe on windows-latest
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies + nuitka
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }
          python -m pip install pyinstaller

      - name: Show env sanity (Python + Tk)
        shell: pwsh
        run: |
          python -V
          python -c "import tkinter, sys; print('tk version:', tkinter.TkVersion); print('argv example:', sys.argv[:1])"

      - name: Build exe with Nuitka
        shell: pwsh
        run: |
          python -m nuitka --onefile --enable-plugin=tk-inter --nofollow-import-to=yt_dlp --include-package-data=yt_dlp downloader.py

      - name: Verify build artifact
        shell: pwsh
        run: |
          if (-not (Test-Path 'downloader.dist\downloader.exe')) {
            Write-Error 'Build failed: downloader.dist\downloader.exe not found'
            exit 1
          } else {
            Write-Host 'Build succeeded: downloader.dist\downloader.exe'
          }

      - name: Package artifact (zip)
        shell: pwsh
        run: |
          if (Test-Path 'artifact.zip') { Remove-Item -Force artifact.zip }
          Compress-Archive -Path 'downloader.dist\downloader.exe' -DestinationPath 'artifact.zip' -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: artifact.zip
